app_lucky_number:
  path: /lucky/number 
  controller: App\Controller\LuckyController::number

app_lucky_save:
    path: /lucky/save
    controller: App\Controller\LuckyController::save
    methods: [POST]
